### ISSUE TITLE
(cli) display board with room mesh

### ISSUE THREAD

**Issue by icburns** [Drakmyth/Slalom-HoloChess#18]
If we had a hololens, our game board would be projected into the user's field of view. Unfortunately the emulator doesn't have a reality to augment unless a spacial mapping mesh is explicitly handed down to the client. Until we hook up the mesh from hololens to our client, the emulator will just present our holograms in a void space, and that's no good. I'd consider this issue resolved if we can see the board in the context of a room mesh from the emulator. While out of scope here, this work should set us along the path to placing the board on a flat surface in reality.

**Comment by ainsleyh** [comment]
closed with latest commit
