### ISSUE TITLE
Put holograms in space (cli)

### ISSUE THREAD

**Issue by icburns** [Drakmyth/Slalom-HoloChess#6]
display the 8 hologram monsters in the simulator.

**Comment by icburns** [comment]
Working on getting some nicer models. Options are:
1. Just use low poly models readily available to us
2. Dig into game assets from SWG, SWTOR, etc
3. Buy some cheap miniatures, and process models ourselves

**Comment by Drakmyth** [comment]
Maybe use the low-poly ones just to get them rendering. Once converted they're just .obj models so we can swap them out with nicer, higher-res ones afterwards.

**Comment by icburns** [comment]
Following an evening of hoop jumping and grinding, we have some high poly meshes for each monster and the game table (not sure how well the latter will scale though). I know textures exist for these, and evidence would suggest textures are embedded somewhere [in the mesh file](http://i.makeagif.com/media/5-05-2014/zAfH3e.gif), but I need to find the right hacky modding software from the mid 2000s to convert the file types correctly.
